### ISSUE TITLE
Failed loading previous saved rpn weights.

### ISSUE THREAD

**Issue by chamecall** [kentaroy47/frcnn-from-scratch-with-keras#13] opened 2019-07-18 16:56 UTC
I launched train_rpn.py script, gave some weights files.
Next I launch the train_frcnn.py and type 
` python3 train_frcnn.py --network vgg -p  'packaging1_voc' --rpn 'models/rpn/rpn.vgg.weights.02-0.06.hdf5'
`
but my weights don't load.
What's the problem?
I give here 
`    model_rpn = model_rpn.load_weights(options.rpn_weight_path)`
model_rpn as None
and loop with next errors:
`Exception: 'NoneType' object has no attribute 'train_on_batch'
Exception: 'NoneType' object has no attribute 'train_on_batch'
Exception: 'NoneType' object has no attribute 'train_on_batch'
Exception: 'NoneType' object has no attribute 'train_on_batch'
Exception: 'NoneType' object has no attribute 'train_on_batch'
Exception: 'NoneType' object has no attribute 'train_on_batch'
Exception: 'NoneType' object has no attribute 'train_on_batch'
Exception: 'NoneType' object has no attribute 'train_on_batch'
`
etc.

**Comment by kentaroy47** [comment] 2019-07-19 05:52
thanks for pointing out. duplicate of #12

**Comment by chamecall** [comment] 2019-07-19 07:32
> thanks for pointing out. duplicate of #12

is there any solution?

**Comment by kentaroy47** [comment] 2019-07-19 08:38
you can now specify what model to load. 

look at readme on test_frcnn.py.

**Closed** 2019-07-19 08:56 UTC
Labels: duplicate
